Added sudo switch to du so that it's the only bit that runs as sudo. Updated help and stuff to reflect the addition.

diff --git a/worktop b/worktop
--- a/worktop
+++ b/worktop
@@ -95,6 +95,7 @@ printHelp() {
   printf "Usage [optional args]: \n\n  ${Yel}$(basename "$1") -d <sasworkdir> \n"
   printf "             [-n <directory sizing interval (seconds)>]\n" 
   printf "             [-g <alert/highlight limit (K/M/G)>] \n"
+  printf "             [-s (run as sudo if your user can't read all work dirs)]\n" 
   printf "             [-i <directory where metaindex host file is located>] \n"
   printf "             [-l <target logfile to write stuff to>]${RCol}\n\n"
   printf "Example (size every 7 minutes, highlight anything larger than 70GB): \n\n  ${Yel}$(basename "$0") -d /data/saswork -n 420 -l 70\n\n${RCol}"
@@ -119,13 +120,14 @@ checkEverything() {
   INTERVAL=30
   WORKLIMIT=1000000 # 1gb default
   LOGFILELOC=/dev/null
+  SUDOAS=
 
   # commands to check for 
   requiredThings=("tput" "date" "man" "getopts" "basename" "hostname" "numfmt" 
     "date" "du" "sort" "readarray" "find" "basename" "cut" "xargs" "read" "echo")
   
   # check that the arguments we have are correct and stuff
-  while getopts ":d:n:l:i:g:h" option; do
+  while getopts "d:n:l:i:g:hs" option; do
     case "${option}" in
     d) 
       WORKDIR=${OPTARG};;
@@ -147,6 +149,16 @@ checkEverything() {
     h) 
       printHelp 
       exit 0;;
+    s)
+      printscr "\nThe -s argument was passed, so here comes a sudo prompt: \n"
+      sudo -v
+      if [ $? == 0 ]; then
+        SUDOAS=sudo
+      else
+        printerror "sudoing unsuccessful :("
+        printscr "\n\nYou failed to sudo. ${Yel}worktop${RCol} will run in non-superuser mode."
+        read -p "Hit Enter to continue."
+      fi;;
     \?) 
       printerror "Invalid option -$OPTARG. "
       printscr "\nFor help with this script, type ${Yel}$(basename "$0") -h${RCol}\n"  
@@ -318,7 +330,7 @@ function calculate {
     printstatus "sizing directory" "${BgRed}"
 
     # basically the entire script right here  
-    readarray -t works < <(du -k --max-depth=0 $WORKDIR/*/ | sort -n -r)
+    readarray -t works < <($SUDOAS du -k --max-depth=0 $WORKDIR/*/ 2>/dev/null | sort -n -r)
     
     timerend=$(date +%s%3N)
     sizetime=$(( $timerend - $timerstart ))
@@ -356,7 +368,6 @@ function calculate {
         thisHex=$(echo "${thisDir}" | cut -d "_" -f 2 | cut -b 10-)
         thisHost=$(echo "${thisDir}" | cut -d "_" -f 3)  
         thisPid=$(( 16#${thisHex} )) 
-        echo "${thisHost}_${thisPid}" >> thisdebug
         # check meta user lookup hash
 	if [ ${lookuphash[${thisHost}_${thisPid}]+bla} ] ; then
 	  thisUser=${lookuphash[${thisHost}_${thisPid}]}
@@ -391,7 +402,6 @@ function calculate {
     printsubstatus "$timermsg" 2
     printlog "Sized in ${sizetime}ms, matched in ${theresttime}ms"
     for (( CNTR=0; CNTR<${#works[@]} && CNTR<$dirstoshow; CNTR+=1 )); do
-      # read -p "${rowShade[$CNTR]}For ${CNTR} this"
       printf "${rowShade[$CNTR]}${col1vals[$CNTR]}${CLine}${col2vals[$CNTR]}${col3vals[$CNTR]}${col4vals[$CNTR]}${col5vals[$CNTR]}${RCol}"
     done
     nextupdate=$INTERVAL
